# fly.toml app configuration file generated for elixirschool on 2025-08-02T09:40:13-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'elixirschool'
primary_region = 'atl'
kill_signal = 'SIGTERM'

[build]

[env]
  PORT = '4000'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
