use Mix.Config

config :school_house,
  redirects: %{
    ~r/^\/$/ => "/en",
    ~r/lessons\/basics\/pattern-matching\/?$/ => "lessons/basics/pattern_matching",
    ~r/lessons\/basics\/control-structures\/?$/ => "lessons/basics/control_structures",
    ~r/lessons\/basics\/pipe-operator\/?$/ => "lessons/basics/pipe_operator",
    ~r/lessons\/basics\/date-time\/?$/ => "lessons/basics/date_time",
    ~r/lessons\/basics\/mix-tasks\/?$/ => "lessons/intermediate/mix_tasks",
    ~r/lessons\/basics\/iex-helpers\/?$/ => "lessons/basics/iex_helpers",
    ~r/lessons\/basics\/testing\/?$/ => "lessons/testing/basics",
    ~r/lessons\/advanced\/erlang\/?$/ => "lessons/intermediate/erlang",
    ~r/lessons\/advanced\/error-handling\/?$/ => "lessons/intermediate/error_handling",
    ~r/lessons\/advanced\/escripts\/?$/ => "lessons/intermediate/escripts",
    ~r/lessons\/advanced\/concurrency\/?$/ => "lessons/intermediate/concurrency",
    ~r/lessons\/advanced\/otp-concurrency\/?$/ => "lessons/advanced/otp_concurrency",
    ~r/lessons\/advanced\/otp-supervisors\/?$/ => "lessons/advanced/otp_supervisors",
    ~r/lessons\/advanced\/otp-distribution\/?$/ => "lessons/advanced/otp_distribution",
    ~r/lessons\/advanced\/umbrella-projects\/?$/ => "lessons/advanced/umbrella_projects",
    ~r/lessons\/advanced\/gen-stage\/?$/ => "lessons/data_processing/genstage",
    ~r/lessons\/ecto\/querying\/?$/ => "lessons/ecto/querying_basics",
    ~r/lessons\/specifics\/plug\/?$/ => "lessons/misc/plug",
    ~r/lessons\/specifics\/eex\/?$/ => "lessons/misc/eex",
    ~r/lessons\/specifics\/ets\/?$/ => "lessons/storage/ets",
    ~r/lessons\/specifics\/mnesia\/?$/ => "lessons/storage/mnesia",
    ~r/lessons\/specifics\/debugging\/?$/ => "lessons/misc/debugging",
    ~r/lessons\/specifics\/nerves\/?$/ => "lessons/misc/nerves",
    ~r/lessons\/libraries\/guardian\/?$/ => "lessons/misc/guardian",
    ~r/lessons\/libraries\/poolboy\/?$/ => "lessons/misc/poolboy",
    ~r/lessons\/libraries\/benchee\/?$/ => "lessons/misc/benchee",
    ~r/lessons\/libraries\/bypass\/?$/ => "lessons/testing/bypass",
    ~r/lessons\/libraries\/distillery\/?$/ => "lessons/misc/distillery",
    ~r/lessons\/libraries\/stream-data\/?$/ => "lessons/testing/stream_data",
    ~r/lessons\/libraries\/nimble-publisher\/?$/ => "lessons/misc/nimble_publisher",
    ~r/lessons\/libraries\/mox\/?$/ => "lessons/testing/mox",
    ~r/^\/cb/ => "/zh-hans",
    ~r/^\/tw/ => "/zh-hant",
    ~r/^\/my/ => "/me",
    ~r/^\/jp/ => "/ja",
    ~r/^\/gr/ => "/el"
  }
